### ISSUE TITLE
Filter i loggen

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMlog#4]
Mulighet for filtreringer på b_id, action-type og objekt.

Begrens også i tid?

**Comment by mariusmandal** [comment]
Sjeldent så mange Events (les Max 40), så tror ikke tid er nødvendig

**Comment by AsgeirSH** [comment]
Tilgjengelig kun for admins eller superadmins?

**Comment by AsgeirSH** [comment]
Og trenger vi egentlig action-type? Det ble uansett ganske oversiktlig filtrert på b_id.
![skjermbilde 2016-02-12 kl 10 42 47](https://cloud.githubusercontent.com/assets/1831028/13003343/65721efe-d175-11e5-9ccb-357c6827fc50.png)

**Comment by mariusmandal** [comment]
Hvis man kan mixe og matche parametre er det hensiktsmessig. Se feks hvor mange som er meldt av mønstringen



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox
